// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snwcsfpxrevbvptcxzhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNud2NzZnB4cmV2YnZwdGN4emh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTkzMDgsImV4cCI6MjA2NzIzNTMwOH0.XIYg0RlPSUrzriRtuj-0Mt4_CHiKr13M9ILCmuBfSTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});